<?php return array (
  'keys' => 
  array (
    0 => 'site.index-text',
    1 => 'index.inex-header-title',
    2 => 'index.index-header-subtitle',
    3 => 'site.copy-text',
    4 => 'site.privacy',
    5 => 'site.cookie',
    6 => 'site.terms',
    7 => 'index.rocket-title',
    8 => 'index.rocket-subtitle1',
    9 => 'index.rocket-subtitle2',
    10 => 'index.rocket-subtitle3',
    11 => 'index.rocket-subtitle4',
    12 => 'index.rocket-text1',
    13 => 'index.rocket-text2',
    14 => 'index.rocket-text3',
    15 => 'index.rocket-text4',
    16 => 'site.contact-subtitle',
    17 => 'index.contact-subtitle',
    18 => 'contact.subtitle',
    19 => 'contact.address',
    20 => 'contact.phone',
    21 => 'contact.work',
    22 => 'contact.email',
    23 => 'site.work-title',
    24 => 'work.work-subtitle',
    25 => 'work.work-title',
    26 => 'work.work-service-title1',
    27 => 'work.work-service-title2',
    28 => 'work.work-service-title3',
    29 => 'work.work-service-text1',
    30 => 'work.work-service-text2',
    31 => 'work.work-service-text3',
    32 => 'clients.clients-sub',
    33 => 'team.team-subtitle',
    34 => 'index.index-service-title1',
    35 => 'index.index-service-title2',
    36 => 'index.index-service-title3',
    37 => 'index.index-service-text1',
    38 => 'index.index-service-text2',
    39 => 'index.index-service-text3',
    40 => 'index.index-service-text4',
    41 => 'index.index-service-title4',
  ),
);